import { useState } from 'react';
import { Button } from '../ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/Card';
import { Checkbox } from '../ui/Checkbox';
import { Input } from '../ui/Input';
import { Label } from '../ui/Label';
import { WIDGET_REGISTRY, widgetsForSlot } from '../config/widgets/registry';
import { NAV_ITEM_META } from '../ui/appShellNavigation';

const SLOTS = ['venue.dashboard.kpis', 'event.detail.intelligence', 'couple.portal.hero'] as const;
export function WidgetBuilder({ value, busy, onSave }: { value: any; busy: boolean; onSave: (value: any) => void }) {
  const [widgets, setWidgets] = useState(value ?? {}); const [slot, setSlot] = useState<(typeof SLOTS)[number]>(SLOTS[0]);
  const selected = new Set((widgets[slot]?.widgets ?? []).filter((w: any) => !w.hidden).map((w: any) => w.id));
  const toggle = (id: string) => setWidgets((current: any) => ({ ...current, [slot]: { widgets: selected.has(id) ? [...selected].filter((x) => x !== id).map((id) => ({ id })) : [...selected, id].map((id) => ({ id })) } }));
  return <Card><CardHeader><CardTitle>Widget builder</CardTitle><CardDescription>Choose a surface, then select the widgets users see there.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2">{SLOTS.map((id) => <Button key={id} size="sm" variant={slot === id ? 'default' : 'outline'} onClick={() => setSlot(id)}>{id.replace(/\./g, ' › ')}</Button>)}</div><div className="grid gap-2 md:grid-cols-2">{widgetsForSlot(slot).map((widget) => <label key={widget.id} className="flex gap-3 rounded-lg border border-border p-3"><Checkbox checked={selected.has(widget.id)} onCheckedChange={() => toggle(widget.id)} /><span><strong className="block">{widget.name}</strong><span className="text-sm text-fg-muted">{widget.description}</span></span></label>)}</div><Button isLoading={busy} onClick={() => onSave(widgets)}>Save widgets</Button></CardContent></Card>;
}

export function LayoutBuilder({ value, busy, onSave }: { value: any; busy: boolean; onSave: (value: any) => void }) {
  const [layout, setLayout] = useState(value ?? {}); const items = layout.navItems ?? Object.keys(NAV_ITEM_META).map((id) => ({ id }));
  const setItem = (id: string, hidden: boolean) => setLayout((current: any) => ({ ...current, navItems: items.map((item: any) => item.id === id ? { ...item, hidden } : item) }));
  return <Card><CardHeader><CardTitle>Navigation and features</CardTitle><CardDescription>Choose what appears in the main navigation and set the default sidebar behavior.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 md:grid-cols-2">{items.map((item: any) => <label key={item.id} className="flex items-center justify-between rounded-lg border border-border p-3"><span>{NAV_ITEM_META[item.id]?.label ?? item.id}</span><Checkbox checked={!item.hidden} onCheckedChange={(checked) => setItem(item.id, !checked)} /></label>)}</div><label className="flex items-center gap-3"><Checkbox checked={!!layout.sidebarCollapsedByDefault} onCheckedChange={(checked) => setLayout((current: any) => ({ ...current, sidebarCollapsedByDefault: !!checked }))} /> Collapse sidebar by default</label><Button isLoading={busy} onClick={() => onSave({ ...layout, navItems: items, featureFlags: layout.featureFlags ?? {} })}>Save layout</Button></CardContent></Card>;
}

const FONTS = ['Fraunces', 'Playfair Display', 'Cormorant Garamond', 'Lora', 'Inter', 'Source Sans 3', 'IBM Plex Sans'] as const;
export function BrandingEditor({ value, busy, onSave, onUploadLogo }: { value: any; busy: boolean; onSave: (value: any) => void; onUploadLogo: (file: File) => void }) {
  const [branding, setBranding] = useState(value); const update = (key: string, value: string) => setBranding((current: any) => ({ ...current, [key]: value }));
  return <Card><CardHeader><CardTitle>Organization branding</CardTitle><CardDescription>Set identity, logo, and typography used across the organization and guest portal.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div><Label htmlFor="brand-name">Platform name</Label><Input id="brand-name" value={branding.platformName ?? ''} onChange={(e) => update('platformName', e.target.value)} /></div><div><Label htmlFor="brand-tagline">Tagline</Label><Input id="brand-tagline" value={branding.tagline ?? ''} onChange={(e) => update('tagline', e.target.value)} /></div><div><Label htmlFor="brand-support">Support email</Label><Input id="brand-support" type="email" value={branding.supportEmail ?? ''} onChange={(e) => update('supportEmail', e.target.value)} /></div><div><Label htmlFor="brand-logo">Upload logo</Label><Input id="brand-logo" type="file" accept="image/png,image/jpeg,image/bmp" onChange={(e) => e.target.files?.[0] && onUploadLogo(e.target.files[0])} />{branding.logoUrl && <img className="mt-2 h-12 max-w-40 object-contain" src={branding.logoUrl} alt="Current organization logo" />}</div><div><Label htmlFor="brand-heading">Heading font</Label><select id="brand-heading" className="h-10 w-full rounded-md border border-border bg-surface px-3" value={branding.headingFont ?? ''} onChange={(e) => update('headingFont', e.target.value)}>{FONTS.map((font) => <option key={font}>{font}</option>)}</select></div><div><Label htmlFor="brand-body">Body font</Label><select id="brand-body" className="h-10 w-full rounded-md border border-border bg-surface px-3" value={branding.bodyFont ?? ''} onChange={(e) => update('bodyFont', e.target.value)}>{FONTS.map((font) => <option key={font}>{font}</option>)}</select></div><div className="md:col-span-2"><Button isLoading={busy} onClick={() => onSave(branding)}>Save branding</Button></div></CardContent></Card>;
}
