/**
 * Event Health Command Center.
 *
 * Consolidates the platform's existing intelligence signals into a prioritized,
 * explainable action queue for venue owners/planners:
 *   - risk alerts
 *   - revenue forecast / pipeline health
 *   - vendor reliability
 *   - guest identity duplicate clusters
 *   - RSVP lag
 *   - timeline completeness
 */
import { db } from '../database.js';
import { forecastRepo } from './forecast.js';
import { guestIdentityRepo } from './guestIdentity.js';
import { riskRepo, type RiskSeverity } from './risk.js';
import { vendorScoringRepo } from './vendorScoring.js';
import { healthActionStatesRepo, type HealthActionStateRow } from './healthActionStates.js';

export type HealthActionPriority = 'critical' | 'high' | 'medium' | 'low';
export type HealthActionSource =
  | 'risk'
  | 'forecast'
  | 'vendor_reliability'
  | 'guest_identity'
  | 'rsvp_lag'
  | 'timeline_completeness'
  | 'contracts'
  | 'payments';

export interface HealthCommandAction {
  id: string;
  priority: HealthActionPriority;
  source: HealthActionSource;
  title: string;
  detail: string;
  href: string;
  eventId?: string;
  eventTitle?: string;
  impact: string;
  confidence: 'high' | 'medium' | 'low';
  relatedSignals: string[];
  thresholdExplanation?: string;
  fixCta?: string;
  state?: {
    status: 'open' | 'acknowledged' | 'snoozed' | 'resolved';
    snoozedUntil: string | null;
    assignedTo: string | null;
    note: string | null;
    updatedAt: string;
  };
}

export interface HealthCommandCenter {
  summary: {
    openEvents: number;
    flaggedEvents: number;
    criticalActions: number;
    highActions: number;
    mediumActions: number;
    lowActions: number;
    avgHealthScore: number | null;
    forecastConfidence: 'high' | 'medium' | 'low';
    projectedRevenueCents: number;
    pipelineRevenueCents: number;
    lowReliabilityVendors: number;
    guestDuplicateClusters: number;
    rsvpLagEvents: number;
    timelineIncompleteEvents: number;
  };
  actions: HealthCommandAction[];
  resolvedActions: Array<{ actionId: string; status: string; note: string | null; updatedAt: string }>;
}

interface ActiveEventRow {
  id: string;
  title: string;
  start_date: string | null;
  rsvp_deadline: string | null;
}

const PRIORITY_RANK: Record<HealthActionPriority, number> = {
  critical: 4,
  high: 3,
  medium: 2,
  low: 1,
};

const severityToPriority = (s: RiskSeverity): HealthActionPriority =>
  s === 'critical' ? 'critical' : s === 'warning' ? 'high' : 'medium';

function daysUntil(date: string | null): number | null {
  if (!date) return null;
  const t = new Date(date + 'T00:00:00Z').getTime();
  if (Number.isNaN(t)) return null;
  return Math.ceil((t - Date.now()) / 86_400_000);
}

function dollars(cents: number): string {
  return `$${Math.round(cents / 100).toLocaleString()}`;
}

function thresholdExplanation(source: HealthActionSource): string {
  const map: Record<HealthActionSource, string> = {
    risk: 'Risk alerts are generated from live event health thresholds such as RSVP lag, missing vendors, unsigned contracts, budget variance, and timeline gaps.',
    forecast: 'Forecast actions appear when historical bookings, projected revenue, or open pipeline fall outside confidence or pacing thresholds.',
    vendor_reliability: 'Vendor reliability uses post-event ratings and missing score coverage to protect preferred vendor quality.',
    guest_identity: 'Guest identity actions appear when email, phone, or name matching indicates likely duplicate records.',
    rsvp_lag: 'RSVP lag appears when pending responses exceed 35% close to the RSVP deadline or event date.',
    timeline_completeness: 'Timeline completeness compares event proximity and assigned vendor count against expected run-of-show coverage.',
    contracts: 'Contract alerts appear when sent agreements are missing signatures.',
    payments: 'Payment alerts appear when pending/processing payment milestones are due within 7 days or overdue.',
  };
  return map[source];
}

function pushAction(actions: HealthCommandAction[], action: HealthCommandAction) {
  // Keep ids stable and dedupe if the same signal is generated by multiple passes.
  if (!actions.some((a) => a.id === action.id)) {
    actions.push({
      thresholdExplanation: thresholdExplanation(action.source),
      fixCta: 'Fix this',
      ...action,
    });
  }
}

function withState(action: HealthCommandAction, states: Map<string, HealthActionStateRow>): HealthCommandAction {
  const state = states.get(action.id);
  if (!state) return action;
  return {
    ...action,
    state: {
      status: state.status,
      snoozedUntil: state.snoozed_until,
      assignedTo: state.assigned_to,
      note: state.note,
      updatedAt: state.updated_at,
    },
  };
}

function isVisibleAction(action: HealthCommandAction): boolean {
  const status = action.state?.status;
  if (!status || status === 'open') return true;
  if (status === 'resolved') return false;
  if (status === 'snoozed') {
    const until = action.state?.snoozedUntil;
    return !until || new Date(until).getTime() <= Date.now();
  }
  return true;
}

export const healthCommandRepo = {
  forOrg(orgId: string): HealthCommandCenter {
    const actions: HealthCommandAction[] = [];

    const activeEvents = db.prepare(
      `SELECT id, title, start_date, rsvp_deadline
       FROM events
       WHERE organization_id = ? AND deleted_at IS NULL
         AND status IN ('lead','hold','booked','planning')`,
    ).all(orgId) as ActiveEventRow[];

    // ── Risk alerts (existing explainable event-health model) ─────────────
    const riskyEvents = riskRepo.forOrg(orgId);
    for (const ev of riskyEvents) {
      const top = ev.alerts[0];
      if (!top) continue;
      pushAction(actions, {
        id: `risk:${top.id}`,
        priority: severityToPriority(top.severity),
        source: 'risk',
        eventId: ev.eventId,
        eventTitle: ev.eventTitle,
        title: top.title,
        detail: top.detail,
        href: top.href,
        impact: `Event health score is ${ev.healthScore}/100${ev.daysUntil != null && ev.daysUntil >= 0 ? ` with ${ev.daysUntil} day(s) until event` : ''}.`,
        confidence: 'high',
        relatedSignals: [top.kind, `${top.severity} severity`, `health ${ev.healthScore}`],
      });
    }

    // ── RSVP lag: explicit queue separate from general risk card ──────────
    let rsvpLagEvents = 0;
    for (const ev of activeEvents) {
      const rows = db.prepare(
        `SELECT rsvp_status AS status, COUNT(*) AS n
         FROM guests
         WHERE organization_id = ? AND event_id = ? AND deleted_at IS NULL
         GROUP BY rsvp_status`,
      ).all(orgId, ev.id) as Array<{ status: string; n: number }>;
      const total = rows.reduce((a, r) => a + r.n, 0);
      if (total === 0) continue;
      const pending = rows.find((r) => r.status === 'pending')?.n ?? 0;
      const pendingPct = pending / total;
      const deadlineDays = daysUntil(ev.rsvp_deadline);
      const eventDays = daysUntil(ev.start_date);
      const urgent = (deadlineDays != null && deadlineDays <= 7) || (eventDays != null && eventDays <= 21);
      if (pendingPct >= 0.35 && urgent) {
        rsvpLagEvents += 1;
        pushAction(actions, {
          id: `rsvp_lag:${ev.id}`,
          priority: pendingPct >= 0.6 || (deadlineDays != null && deadlineDays < 0) ? 'critical' : 'high',
          source: 'rsvp_lag',
          eventId: ev.id,
          eventTitle: ev.title,
          title: 'Accelerate RSVP follow-up',
          detail: `${pending} of ${total} guests (${Math.round(pendingPct * 100)}%) are still pending${deadlineDays != null ? `; RSVP deadline is ${deadlineDays < 0 ? `${Math.abs(deadlineDays)} day(s) overdue` : `in ${deadlineDays} day(s)`}` : ''}.`,
          href: `#/events/${ev.id}?tab=guests`,
          impact: 'Improves catering counts, seating accuracy, and late guest communication risk.',
          confidence: 'high',
          relatedSignals: ['pending RSVP ratio', deadlineDays != null ? 'RSVP deadline' : 'event date proximity'],
        });
      }
    }

    // ── Timeline completeness: day-of operational readiness ───────────────
    let timelineIncompleteEvents = 0;
    for (const ev of activeEvents) {
      const eventDays = daysUntil(ev.start_date);
      if (eventDays == null || eventDays < 0 || eventDays > 60) continue;
      const count = (db.prepare(`SELECT COUNT(*) AS n FROM timeline_events WHERE event_id = ?`).get(ev.id) as { n: number }).n;
      const vendorCount = (db.prepare(`SELECT COUNT(*) AS n FROM vendors WHERE event_id = ? AND deleted_at IS NULL`).get(ev.id) as { n: number }).n;
      const expectedMin = Math.max(5, Math.min(12, vendorCount * 2));
      if (count < expectedMin) {
        timelineIncompleteEvents += 1;
        pushAction(actions, {
          id: `timeline_completeness:${ev.id}`,
          priority: eventDays <= 14 && count === 0 ? 'critical' : eventDays <= 30 ? 'high' : 'medium',
          source: 'timeline_completeness',
          eventId: ev.id,
          eventTitle: ev.title,
          title: count === 0 ? 'Build the run-of-show timeline' : 'Complete timeline coverage',
          detail: `${ev.title} has ${count} timeline item(s); expected at least ${expectedMin} based on event proximity and vendor count.`,
          href: `#/events/${ev.id}?tab=timeline`,
          impact: 'Reduces load-in, ceremony, dinner, teardown, and staffing coordination risk.',
          confidence: 'medium',
          relatedSignals: [`${eventDays} days until event`, `${vendorCount} vendor(s)`, `${count} timeline item(s)`],
        });
      }
    }

    // ── Vendor reliability ────────────────────────────────────────────────
    const vendorScores = vendorScoringRepo.scoreAll(orgId);
    const lowReliability = vendorScores.filter((v) => v.ratingCount > 0 && v.reliabilityScore < 70);
    const unratedAssigned = (db.prepare(
      `SELECT COUNT(*) AS n
       FROM vendors
       WHERE organization_id = ? AND deleted_at IS NULL AND event_id IS NOT NULL
         AND id NOT IN (SELECT DISTINCT vendor_id FROM vendor_ratings WHERE organization_id = ?)`,
    ).get(orgId, orgId) as { n: number }).n;
    if (lowReliability.length > 0) {
      const worst = [...lowReliability].sort((a, b) => a.reliabilityScore - b.reliabilityScore)[0];
      pushAction(actions, {
        id: 'vendor_reliability:low_scores',
        priority: lowReliability.length >= 3 ? 'high' : 'medium',
        source: 'vendor_reliability',
        title: 'Review low-reliability vendors',
        detail: `${lowReliability.length} vendor(s) have reliability scores below 70. Lowest: ${worst.name} (${worst.reliabilityScore}/100).`,
        href: '#/vendors',
        impact: 'Helps prevent day-of vendor performance issues and improves preferred vendor recommendations.',
        confidence: 'medium',
        relatedSignals: ['vendor ratings', 'quality/timeliness/communication scores'],
      });
    } else if (unratedAssigned >= 3) {
      pushAction(actions, {
        id: 'vendor_reliability:unrated_assigned',
        priority: 'low',
        source: 'vendor_reliability',
        title: 'Collect vendor reliability ratings',
        detail: `${unratedAssigned} assigned vendor(s) have no post-event reliability ratings yet.`,
        href: '#/vendors',
        impact: 'Improves future vendor matching and risk scoring confidence.',
        confidence: 'low',
        relatedSignals: ['assigned vendors', 'missing vendor ratings'],
      });
    }

    // ── Guest identity duplicate clusters ─────────────────────────────────
    const duplicateClusters = guestIdentityRepo.findDuplicates(orgId);
    const actionableDupes = duplicateClusters.filter((c) => c.hasInEventDuplicate || c.confidence === 'high');
    if (actionableDupes.length > 0) {
      const first = actionableDupes[0];
      pushAction(actions, {
        id: 'guest_identity:duplicates',
        priority: first.hasInEventDuplicate ? 'high' : 'medium',
        source: 'guest_identity',
        title: 'Resolve duplicate guest identities',
        detail: `${actionableDupes.length} duplicate guest cluster(s) detected; largest has ${first.members.length} records and ${first.confidence} confidence.`,
        href: '#/guests',
        impact: 'Prevents duplicate invitations, inaccurate counts, and seating/meal conflicts.',
        confidence: first.confidence,
        relatedSignals: first.signals.map((s) => `matched ${s}`),
      });
    }

    // ── Forecast / pipeline health ────────────────────────────────────────
    const forecast = forecastRepo.forOrg(orgId, 24, 6);
    if (forecast.meta.confidence === 'low') {
      pushAction(actions, {
        id: 'forecast:low_confidence',
        priority: 'low',
        source: 'forecast',
        title: 'Improve forecast confidence',
        detail: `Only ${forecast.meta.monthsOfHistory} month(s) have booking history. Add/complete more events to improve seasonal revenue predictions.`,
        href: '#/reports',
        impact: 'Better history improves lead pacing, rate strategy, and cashflow planning.',
        confidence: 'high',
        relatedSignals: ['forecast confidence', 'booking history'],
      });
    }
    if (forecast.trend.direction === 'down' && forecast.meta.confidence !== 'low') {
      pushAction(actions, {
        id: 'forecast:down_trend',
        priority: 'medium',
        source: 'forecast',
        title: 'Revenue trend is softening',
        detail: `Projected revenue is trending down ${Math.abs(forecast.trend.growthPct)}% over the next ${forecast.meta.horizonMonths} months.`,
        href: '#/reports',
        impact: 'Use lead-source ROI and smart-rate recommendations to protect forward bookings.',
        confidence: forecast.meta.confidence,
        relatedSignals: ['revenue forecast', 'seasonality', 'pipeline'],
      });
    }
    const projected = forecast.totals.projectedRevenueCents;
    const pipeline = forecast.pipeline.openRevenueCents;
    if (projected > 0 && pipeline > 0 && pipeline < projected * 0.5) {
      pushAction(actions, {
        id: 'forecast:pipeline_gap',
        priority: 'medium',
        source: 'forecast',
        title: 'Pipeline trails revenue projection',
        detail: `Open pipeline is ${dollars(pipeline)} against ${dollars(projected)} projected for the next ${forecast.meta.horizonMonths} months.`,
        href: '#/events',
        impact: 'Follow up with leads/holds to close the gap between forecast and booked revenue.',
        confidence: forecast.meta.confidence,
        relatedSignals: ['projected revenue', 'open pipeline revenue'],
      });
    }

    // ── Contracts / payments ─────────────────────────────────────────────
    const unsignedContracts = db.prepare(
      `SELECT c.id, c.event_id, c.title, e.title AS event_title
       FROM contracts c JOIN events e ON e.id = c.event_id
       WHERE c.organization_id = ? AND c.status = 'sent' AND e.deleted_at IS NULL
       LIMIT 10`,
    ).all(orgId) as Array<{ id: string; event_id: string; title: string; event_title: string }>;
    for (const c of unsignedContracts) {
      pushAction(actions, {
        id: `contract_unsigned:${c.id}`,
        priority: 'high',
        source: 'contracts',
        eventId: c.event_id,
        eventTitle: c.event_title,
        title: 'Contract missing signature',
        detail: `“${c.title}” is sent but not signed yet.`,
        href: `#/events/${c.event_id}?tab=contracts`,
        impact: 'Unsigned contracts can delay deposits, planning approvals, and event confirmation.',
        confidence: 'high',
        relatedSignals: ['contract status sent', 'missing signature'],
      });
    }
    const duePayments = db.prepare(
      `SELECT p.id, p.event_id, p.amount_cents, p.metadata, e.title AS event_title
       FROM payment_links p JOIN events e ON e.id = p.event_id
       WHERE p.organization_id = ? AND p.status IN ('pending','processing') AND e.deleted_at IS NULL
       LIMIT 20`,
    ).all(orgId) as Array<{ id: string; event_id: string; amount_cents: number; metadata: string; event_title: string }>;
    for (const p of duePayments) {
      let dueDate: string | undefined;
      try { dueDate = JSON.parse(p.metadata || '{}').dueDate; } catch {}
      const dueDays = daysUntil(dueDate ?? null);
      if (dueDays != null && dueDays <= 7) {
        pushAction(actions, {
          id: `payment_due:${p.id}`,
          priority: dueDays < 0 ? 'critical' : 'high',
          source: 'payments',
          eventId: p.event_id,
          eventTitle: p.event_title,
          title: dueDays < 0 ? 'Payment milestone overdue' : 'Payment milestone due soon',
          detail: `${dollars(p.amount_cents)} payment is ${dueDays < 0 ? `${Math.abs(dueDays)} day(s) overdue` : `due in ${dueDays} day(s)`}.`,
          href: `#/events/${p.event_id}?tab=budget`,
          impact: 'Improves cashflow visibility and reduces final-balance surprises.',
          confidence: 'high',
          relatedSignals: ['payment milestone', 'due date'],
        });
      }
    }

    const states = new Map(healthActionStatesRepo.listForOrg(orgId).map((s) => [s.action_id, s] as const));
    const statefulActions = actions.map((a) => withState(a, states)).filter(isVisibleAction);
    const resolvedActions = healthActionStatesRepo.resolvedForOrg(orgId).map((s) => ({
      actionId: s.action_id,
      status: s.status,
      note: s.note,
      updatedAt: s.updated_at,
    }));

    const ordered = statefulActions.sort((a, b) =>
      PRIORITY_RANK[b.priority] - PRIORITY_RANK[a.priority] ||
      a.title.localeCompare(b.title),
    );
    const healthScores = riskyEvents.map((r) => r.healthScore);
    const counts = ordered.reduce((acc, a) => {
      acc[a.priority] += 1;
      return acc;
    }, { critical: 0, high: 0, medium: 0, low: 0 } as Record<HealthActionPriority, number>);

    return {
      summary: {
        openEvents: activeEvents.length,
        flaggedEvents: riskyEvents.length,
        criticalActions: counts.critical,
        highActions: counts.high,
        mediumActions: counts.medium,
        lowActions: counts.low,
        avgHealthScore: healthScores.length ? Math.round(healthScores.reduce((a, b) => a + b, 0) / healthScores.length) : null,
        forecastConfidence: forecast.meta.confidence,
        projectedRevenueCents: forecast.totals.projectedRevenueCents,
        pipelineRevenueCents: forecast.pipeline.openRevenueCents,
        lowReliabilityVendors: lowReliability.length,
        guestDuplicateClusters: actionableDupes.length,
        rsvpLagEvents,
        timelineIncompleteEvents,
      },
      actions: ordered.slice(0, 20),
      resolvedActions,
    };
  },
};
