import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, Compass, FileUp, Plus, Ruler, ShieldCheck, TentTree } from 'lucide-react';
import { venuesSdk } from '../../../sdk/venues';
import { sdk } from '../../../sdk';
import { Button } from '../../../ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../ui/Card';
import { Input } from '../../../ui/Input';
import { Label } from '../../../ui/Label';
import { useToast } from '../../../ui/Toast';

const TEMPLATES = [
  { key: 'ceremony', label: 'Ceremony', icon: Compass, environment: 'indoor', description: 'Aisle, focal point, processional entrance, guest seating, accessible route, and exits.' },
  { key: 'cocktail', label: 'Cocktail hour', icon: Plus, environment: 'indoor', description: 'Bar, cocktail tables, food stations, circulation, and service zones.' },
  { key: 'reception', label: 'Reception', icon: ShieldCheck, environment: 'indoor', description: 'Tables, dance floor, bar, stage, service, exits, and accessible route.' },
  { key: 'outdoor_tent', label: 'Outdoor / tent', icon: TentTree, environment: 'outdoor', description: 'Tent boundary, power, loading, weather fallback, exits, and restroom zone.' },
] as const;
const FOOTPRINTS = [
  ['rectangle', 'Rectangle'], ['l_shape', 'L-shape'], ['u_shape', 'U-shape'], ['courtyard', 'Courtyard'], ['tent', 'Tent'], ['open_boundary', 'Open boundary'], ['custom', 'Custom outline'],
] as const;
const FEATURES = [
  ['entrance', 'Guest entrance / door'], ['exit', 'Emergency exit'], ['accessible_route', 'Accessible route'], ['power', 'Power / cable point'], ['loading', 'Service / loading entry'], ['window', 'Window'], ['column', 'Column / pillar'], ['built_in_bar', 'Built-in bar'], ['stage', 'Built-in stage'], ['restroom', 'Restroom direction'], ['stairs_elevator', 'Stairs / elevator'], ['partition', 'Partition'], ['fireplace', 'Fireplace'], ['screen', 'Screen'], ['outdoor_feature', 'Outdoor / parking feature'],
] as const;
type StartPath = 'template' | 'measure' | 'upload';

function baseZones(template: string, width: number, height: number) {
  const centerX = width / 2; const centerY = height / 2;
  const zones: any[] = [];
  if (template === 'ceremony') zones.push({ id: 'aisle', type: 'accessible_route', x: centerX - 3, y: 0, width: 6, height }, { id: 'focal', type: 'ceremony_focal', x: centerX - 10, y: 4, width: 20, height: 8 });
  if (template === 'cocktail') zones.push({ id: 'bar', type: 'bar', x: 4, y: 4, width: 18, height: 6 }, { id: 'service', type: 'service_zone', x: Math.max(4, width - 18), y: 4, width: 14, height: 8 });
  if (template === 'reception') zones.push({ id: 'dance', type: 'dance_floor', x: centerX - 12, y: centerY - 9, width: 24, height: 18 }, { id: 'head', type: 'head_table', x: centerX - 14, y: 4, width: 28, height: 5 });
  if (template === 'outdoor_tent') zones.push({ id: 'tent', type: 'tent_boundary', x: 4, y: 4, width: Math.max(8, width - 8), height: Math.max(8, height - 8) }, { id: 'weather', type: 'weather_fallback', x: Math.max(4, width - 18), y: Math.max(4, height - 12), width: 12, height: 6 });
  return zones;
}

function shapePoints(kind: string, width: number, height: number) {
  if (kind === 'l_shape') return [{ x: 0, y: 0 }, { x: width, y: 0 }, { x: width, y: height * .55 }, { x: width * .55, y: height * .55 }, { x: width * .55, y: height }, { x: 0, y: height }];
  if (kind === 'u_shape' || kind === 'courtyard') return [{ x: 0, y: 0 }, { x: width, y: 0 }, { x: width, y: height }, { x: width * .65, y: height }, { x: width * .65, y: height * .38 }, { x: width * .35, y: height * .38 }, { x: width * .35, y: height }, { x: 0, y: height }];
  return [{ x: 0, y: 0 }, { x: width, y: 0 }, { x: width, y: height }, { x: 0, y: height }];
}

async function readUnderlay(file: File) {
  const toDataUri = () => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
  if (file.type !== 'application/pdf') return { dataUri: await toDataUri() };
  const sourceDataUri = await toDataUri();
  const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const pdf = await pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise;
  const page = await pdf.getPage(1); const viewport = page.getViewport({ scale: 1.5 });
  const canvas = document.createElement('canvas'); canvas.width = Math.ceil(viewport.width); canvas.height = Math.ceil(viewport.height);
  await page.render({ canvas, canvasContext: canvas.getContext('2d')!, viewport }).promise;
  return { dataUri: canvas.toDataURL('image/png'), originalPdf: { dataUri: sourceDataUri, name: file.name } };
}

export function VenueSpaceScaffoldWizard({ orgId, onSelectVenue }: { orgId: string; onSelectVenue: (venue: any) => void }) {
  const { toast } = useToast(); const qc = useQueryClient();
  const [path, setPath] = useState<StartPath | null>(null); const [step, setStep] = useState(1);
  const [template, setTemplate] = useState<(typeof TEMPLATES)[number]['key']>('reception'); const [footprint, setFootprint] = useState('rectangle');
  const [name, setName] = useState(''); const [width, setWidth] = useState(80); const [height, setHeight] = useState(60); const [capacity, setCapacity] = useState(120); const [units, setUnits] = useState<'imperial' | 'metric'>('imperial');
  const [features, setFeatures] = useState<string[]>([]); const [referenceFile, setReferenceFile] = useState<File | null>(null); const [approvalReason, setApprovalReason] = useState('');
  const { data } = useQuery({ queryKey: ['venues', orgId], queryFn: () => venuesSdk.list(orgId) }); const { data: eventData } = useQuery({ queryKey: ['events', orgId], queryFn: () => sdk.events.list(orgId) }); const [eventId, setEventId] = useState('');
  const create = useMutation({
    mutationFn: async () => {
      const templateItem = TEMPLATES.find((item) => item.key === template)!;
      const permanent = features.map((feature, index) => ({ id: `feature-${feature}`, type: feature, x: Math.round(width * (.15 + (index % 4) * .2)), y: Math.round(height * (.15 + Math.floor(index / 4) * .2)), width: feature === 'entrance' || feature === 'exit' ? 6 : 3, height: 3 }));
      const zones = [...baseZones(template, width, height), ...features.filter((feature) => ['exit', 'accessible_route', 'power', 'loading'].includes(feature)).map((type, index) => ({ id: `zone-${type}`, type, x: Math.round(width * (.1 + index * .2)), y: Math.round(height * .8), width: type === 'accessible_route' ? 6 : 4, height: type === 'accessible_route' ? Math.max(8, height * .6) : 4 }))];
      const masterLayout = { walls: [{ id: 'boundary', points: shapePoints(footprint, width, height).flatMap((point) => [point.x, point.y]).concat([0, 0]) }], doors: permanent.filter((item) => item.type === 'entrance' || item.type === 'exit'), windows: permanent.filter((item) => item.type === 'window'), pillars: permanent.filter((item) => item.type === 'column'), fixedFeatures: permanent.filter((item) => !['entrance', 'exit', 'window', 'column'].includes(item.type)), zones };
      const result = await venuesSdk.create(orgId, { name: name || templateItem.label, templateKey: path === 'template' ? template : 'custom', category: template, environment: footprint === 'tent' || footprint === 'open_boundary' ? 'outdoor' : templateItem.environment as any, width, height, canvasWidth: width, canvasHeight: height, capacity, unitSystem: units, approvalStatus: 'draft', shape: { kind: footprint, points: shapePoints(footprint, width, height) }, masterLayout, metadata: { setupPath: path, measurementStatus: path === 'measure' ? 'measured' : path === 'upload' ? 'reference_pending_calibration' : 'template', permanentFeatures: features, readinessRequired: ['exit', 'accessible_route', 'power', 'loading'] } });
      if (referenceFile) { const underlay = await readUnderlay(referenceFile); await venuesSdk.uploadUnderlay(result.venue.id, underlay.dataUri, underlay.originalPdf); }
      return result;
    },
    onSuccess: ({ venue }) => { qc.invalidateQueries({ queryKey: ['venues', orgId] }); onSelectVenue(venue); toast({ title: 'Venue space draft created', description: 'Use Edit details for precise adjustments; review readiness before approval.', variant: 'success' }); setName(''); setPath(null); setStep(1); setReferenceFile(null); setFeatures([]); },
    onError: (e: any) => toast({ title: 'Could not create space', description: e.message, variant: 'destructive' }),
  });
  const incomplete = (venue: any) => { const layout = typeof venue.master_layout === 'string' ? JSON.parse(venue.master_layout || '{}') : venue.master_layout || {}; const types = new Set((layout.zones || []).map((zone: any) => zone.type)); return ['exit', 'accessible_route', 'power', 'loading'].filter((item) => !types.has(item)); };
  async function approveScaffold(venue: any) { const missing = incomplete(venue); if (missing.length && !approvalReason.trim()) { toast({ title: 'Readiness review needed', description: `Missing ${missing.join(', ')}. Add an override reason to approve anyway.`, variant: 'destructive' }); return; } try { const metadata = typeof venue.metadata === 'string' ? JSON.parse(venue.metadata || '{}') : venue.metadata || {}; await venuesSdk.update(venue.id, { approvalStatus: 'approved', metadata: { ...metadata, ...(missing.length ? { approvalOverrideReason: approvalReason.trim(), approvalOverrideMissing: missing } : {}) } }); qc.invalidateQueries({ queryKey: ['venues', orgId] }); onSelectVenue({ ...venue, approval_status: 'approved' }); toast({ title: 'Scaffold approved', description: missing.length ? 'Approved with the venue manager readiness override recorded.' : 'Event layouts can now use this space.', variant: 'success' }); } catch (e: any) { toast({ title: 'Could not approve scaffold', description: e.message, variant: 'destructive' }); } }
  async function createEventLayout(venue: any) { if (!eventId) { toast({ title: 'Choose an event first', description: 'Select the event that will use this space.', variant: 'destructive' }); return; } try { const result = await venuesSdk.createEventLayout(venue.id, eventId) as { layout: { name: string } }; toast({ title: 'Event layout created', description: `Created ${result.layout.name} from the approved scaffold.`, variant: 'success' }); window.location.hash = `#/events/${eventId}?tab=layout`; } catch (e: any) { toast({ title: 'Could not create event layout', description: e.message, variant: 'destructive' }); } }
  const toggleFeature = (feature: string) => setFeatures((current) => current.includes(feature) ? current.filter((item) => item !== feature) : [...current, feature]);

  return <Card><CardHeader><CardTitle>Venue Space Setup</CardTitle><CardDescription>Create a dependable reusable space without drawing from scratch. Venue staff can refine it later in Edit details.</CardDescription></CardHeader><CardContent className="space-y-5">
    {!path && <div className="grid gap-3 md:grid-cols-3"><button type="button" onClick={() => setPath('template')} className="rounded-xl border border-border p-4 text-left hover:border-brand"><Compass className="mb-2 h-6 w-6 text-brand"/><strong className="block">Use a wedding template</strong><span className="mt-1 block text-xs text-fg-muted">Start with ceremony, cocktail, reception, or tent essentials.</span></button><button type="button" onClick={() => setPath('upload')} className="rounded-xl border border-border p-4 text-left hover:border-brand"><FileUp className="mb-2 h-6 w-6 text-brand"/><strong className="block">Upload a floor plan</strong><span className="mt-1 block text-xs text-fg-muted">Use a PDF or image as a locked reference, then calibrate it.</span></button><button type="button" onClick={() => setPath('measure')} className="rounded-xl border-2 border-brand bg-brand-soft/20 p-4 text-left"><Ruler className="mb-2 h-6 w-6 text-brand"/><strong className="block">Measure the space <span className="text-xs">Recommended</span></strong><span className="mt-1 block text-xs text-fg-muted">Enter on-site measurements and add permanent features.</span></button></div>}
    {path && <><div className="flex items-center justify-between text-xs text-fg-muted"><span>Step {step} of 3 · {path === 'measure' ? 'Measure the space' : path === 'upload' ? 'Reference plan setup' : 'Wedding template setup'}</span><button className="underline" onClick={() => { setPath(null); setStep(1); }}>Choose another start</button></div>
      {step === 1 && <div className="space-y-4">{path === 'template' && <div className="grid gap-3 md:grid-cols-4">{TEMPLATES.map((item) => { const Icon = item.icon; return <button key={item.key} type="button" onClick={() => setTemplate(item.key)} className={`rounded-xl border p-3 text-left ${template === item.key ? 'border-brand bg-brand-soft/30' : 'border-border'}`}><Icon className="mb-1 h-5 w-5 text-brand"/><strong className="block text-sm">{item.label}</strong><span className="block text-[10px] text-fg-muted">{item.description}</span></button>; })}</div>}<div className="grid gap-4 md:grid-cols-4"><div><Label htmlFor="space-name">Space name</Label><Input id="space-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="Grand Ballroom"/></div><div><Label htmlFor="space-width">Length ({units === 'imperial' ? 'ft' : 'm'})</Label><Input id="space-width" type="number" min="1" value={width} onChange={(e) => setWidth(Number(e.target.value))}/></div><div><Label htmlFor="space-height">Width ({units === 'imperial' ? 'ft' : 'm'})</Label><Input id="space-height" type="number" min="1" value={height} onChange={(e) => setHeight(Number(e.target.value))}/></div><div><Label htmlFor="space-capacity">Maximum guests</Label><Input id="space-capacity" type="number" min="0" value={capacity} onChange={(e) => setCapacity(Number(e.target.value))}/></div></div>{path === 'upload' && <div><Label htmlFor="space-reference">Reference plan (PNG, JPEG, or PDF)</Label><Input id="space-reference" type="file" accept="image/png,image/jpeg,application/pdf" onChange={(e) => setReferenceFile(e.target.files?.[0] || null)}/><p className="mt-1 text-xs text-fg-muted">The original PDF is retained; its first page becomes a locked canvas reference.</p></div>}<div className="flex items-center gap-4"><label className="flex items-center gap-2 text-sm"><input type="radio" checked={units === 'imperial'} onChange={() => setUnits('imperial')}/> Feet / inches</label><label className="flex items-center gap-2 text-sm"><input type="radio" checked={units === 'metric'} onChange={() => setUnits('metric')}/> Metric</label><Button className="ml-auto" onClick={() => setStep(2)}>Continue</Button></div></div>}
      {step === 2 && <div className="space-y-4"><div><Label>Footprint</Label><div className="mt-2 flex flex-wrap gap-2">{FOOTPRINTS.map(([id, label]) => <button type="button" key={id} onClick={() => setFootprint(id)} className={`rounded-full border px-3 py-1.5 text-sm ${footprint === id ? 'border-brand bg-brand-soft text-brand' : 'border-border'}`}>{label}</button>)}</div><p className="mt-2 text-xs text-fg-muted">Use a simple footprint now. Custom outline opens in Edit details after this draft is created.</p></div><div><Label>Permanent features and operational details</Label><p className="mt-1 text-xs text-fg-muted">Select what exists. The draft adds editable placeholders; use Edit details for exact placement.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{FEATURES.map(([id, label]) => <label key={id} className="flex items-center gap-2 rounded border border-border p-2 text-sm"><input type="checkbox" checked={features.includes(id)} onChange={() => toggleFeature(id)}/>{label}</label>)}</div></div><div className="flex justify-between"><Button variant="secondary" onClick={() => setStep(1)}>Back</Button><Button onClick={() => setStep(3)}>Review setup</Button></div></div>}
      {step === 3 && <div className="space-y-4"><div className="rounded-lg border border-border bg-surface-2 p-4"><strong>{name || TEMPLATES.find((item) => item.key === template)?.label}</strong><p className="mt-1 text-sm text-fg-muted">{width} × {height} {units === 'imperial' ? 'ft' : 'm'} · {capacity} guest maximum · {footprint.replace('_', ' ')}</p><p className="mt-2 text-xs text-fg-muted">{features.length ? `${features.length} permanent feature(s) selected` : 'No permanent features selected yet'} · Advanced editing remains available after creation.</p></div><div className="rounded-lg border border-warning/30 bg-warning-soft/20 p-3 text-sm"><strong>Readiness review</strong><p className="mt-1 text-fg-muted">Recommended before approval: emergency exit, accessible route, power/cable point, and service/loading entry. Missing details can be added in Edit details; managers may approve with a documented override.</p></div><div className="flex justify-between"><Button variant="secondary" onClick={() => setStep(2)}>Back</Button><Button isLoading={create.isPending} onClick={() => create.mutate()}><Ruler className="h-4 w-4"/> Create draft scaffold</Button></div></div>}
    </>}
    <div className="flex flex-wrap items-center gap-3 rounded-lg border border-border p-3"><Label htmlFor="scaffold-event">Create event layout from an approved space</Label><select id="scaffold-event" className="h-10 min-w-56 rounded-md border border-border bg-surface px-3" value={eventId} onChange={(e) => setEventId(e.target.value)}><option value="">Choose event…</option>{eventData?.events?.map((event: any) => <option key={event.id} value={event.id}>{event.title}</option>)}</select></div>
    {data?.venues?.length ? <div className="rounded-lg border border-border p-3 text-sm"><strong>Existing spaces</strong><div className="mt-2 grid gap-2 md:grid-cols-2">{data.venues.map((venue) => { const missing = venue.approval_status === 'approved' ? [] : incomplete(venue); return <div key={venue.id} role="button" tabIndex={0} onClick={() => onSelectVenue(venue)} className="rounded border border-border bg-surface-2 p-3 cursor-pointer hover:border-brand"><div className="flex justify-between gap-2"><span>{venue.name} · {venue.width}×{venue.height} · {venue.capacity} guests</span><span className={venue.approval_status === 'approved' ? 'text-success' : 'text-warning'}>{venue.approval_status === 'approved' ? 'Approved' : 'Draft'}</span></div>{missing.length > 0 && <p className="mt-2 text-xs text-warning">Needs review: {missing.join(', ')}</p>}{venue.approval_status !== 'approved' && <><Input className="mt-2" aria-label={`Approval override reason for ${venue.name}`} value={approvalReason} onClick={(e) => e.stopPropagation()} onChange={(e) => setApprovalReason(e.target.value)} placeholder={missing.length ? 'Manager override reason (only if approving incomplete space)' : 'Optional approval note'}/><Button size="xs" className="mt-2" onClick={(e) => { e.stopPropagation(); void approveScaffold(venue); }}><CheckCircle2 className="h-3 w-3"/> Approve scaffold</Button></>}{venue.approval_status === 'approved' && <Button size="xs" className="mt-2" onClick={(e) => { e.stopPropagation(); void createEventLayout(venue); }}>Create event layout</Button>}</div>; })}</div></div> : null}
  </CardContent></Card>;
}
