import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const base = 'http://localhost:3000';
const issues = [];
page.on('console', m => { if (m.type() === 'error') issues.push('[console] ' + m.text().slice(0, 200)); });
page.on('pageerror', e => issues.push('[pageerror] ' + String(e).slice(0, 200)));
await page.goto(base + '/login');
await page.getByLabel(/email/i).fill('owner@demo.local');
await page.locator('#pw').fill('wedding123');
await page.getByRole('button', { name: 'Sign in securely' }).click();
await page.waitForTimeout(3500);
const token = await page.evaluate(() => localStorage.getItem('wedding-jwt'));
const orgs = await page.evaluate(async (t) => (await fetch('/api/orgs', { headers: { Authorization: `Bearer ${t}` } })).json(), token);
const orgId = orgs.organizations[0].id;
const evs = await page.evaluate(async ({t,o}) => (await fetch(`/api/orgs/${o}/events`, { headers: { Authorization: `Bearer ${t}` } })).json(), {t:token,o:orgId});
const demo = (evs.events||evs).find(e=>e.title.includes('Smith & Jones'));
await page.goto(`${base}/#/events/${demo.id}?tab=budget`);
await page.waitForTimeout(3000);
const txt = await page.evaluate(() => document.body.innerText);
const lines = txt.split('\n').map(l=>l.trim()).filter(l=>l && l.length<100);
console.log('BUDGET TAB FULL SAMPLE:', JSON.stringify(lines.slice(40, 90), null, 1));
console.log('ISSUES:', JSON.stringify(issues, null, 1));
await browser.close();
